name: kafka-connect-storage-cloud
lang: java
lang_version: 8
git:
  enable: true
codeowners:
  enable: true
semaphore:
  enable: true
  pipeline_type: cp
  cve_scan: true
  extra_secrets: ["connect_s3sink_it"]
  extra_deploy_args: "-Dcloud -Pjenkins"
  extra_build_args: "-Dcloud -Pjenkins"
  run_pint_merge: true
