name: kafka-connect-storage-cloud
lang: java
lang_version: unknown
git:
  enable: true
codeowners:
  enable: true
semaphore:
  enable: true
  pipeline_type: cp
  cve_scan: true
  extra_secrets: ["connect_s3sink_it"]
