#!/usr/bin/groovy

pipeline {
  agent {
    kubernetes {
      defaultContainer 'maven'
      yaml '''
apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins/build: emb-m2
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: jenkins/build
            operator: In
            values:
            - emb-m2
        topologyKey: "kubernetes.io/hostname"
  volumes:
  - name: m2-repo
    persistentVolumeClaim:
      claimName: emb-m2-repo
  serviceAccountName: jenkins-codeartifact
  containers:
  - name: maven
    image: maven:3.8.1-openjdk-11
    command:
    - cat
    tty: true
    volumeMounts:
      - mountPath: "/home/jenkins/.m2"
        name: m2-repo
  - name: aws
    image: amazon/aws-cli:2.2.18
    command:
    - cat
    tty: true
'''
    }
  }

  stages {
    stage('init') {
      steps {
        withFolderProperties {
          writeFile file: 'settings.xml', text: env.MAVEN_SETTINGS
          container('aws') {
            withAWS(role: env.AWS_CODEARTIFACT_ASSUME_ROLE, useNode: true) {
              script {
                env.CODEARTIFACT_AUTH_TOKEN = sh(script:"aws codeartifact get-authorization-token --domain emnify --domain-owner ${env.AWS_CODEARTIFACT_OWNER} --query authorizationToken --output text", returnStdout: true)
              }
            }
          }
        }
      }
    }
    stage('Build and test') {
      steps {
        sh 'mvn test -q -B -s settings.xml'
      }
    }
    stage('Deploy') {
      when { branch 'emnify-10.x' }
      steps {
        sh 'mvn deploy -q -B -s settings.xml -P standalone -DskipTests -Dspotbugs.skip=true'
      }
    }
  }
}